[build]
command = "npm run build"
publish = "dist"

[[headers]]
for = "/*.js"
[headers.values]
Content-Type = "application/javascript; charset=utf-8"

[[headers]]
for = "/*.mjs"
[headers.values]
Content-Type = "application/javascript; charset=utf-8"

[[headers]]
for = "/*.ts"
[headers.values]
Content-Type = "text/typescript"

[[headers]]
for = "/*.tsx"
[headers.values]
Content-Type = "text/typescript"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
